language: R

os:
  - osx

r:
  - "3.3"
  - "3.4"

install:
  - Rscript -e 'install.packages(c("data.table","ggplot2","gdata","survival"))'

script:
  - Rscript ./helper_functions.R
  - Rscript ./plot_themes.R
