language: R

os:
  - osx

r:
  - "3.3"
  - "3.4"

install:
  - Rscript -e 'install.packages(c("data.table","ggplot2","gdata","survival"))'
  - Rscript -e 'source("./helper_functions.R")'

script:
  - make test
